### ISSUE TITLE
[error] Uncaught TypeError: api.duplex.destroy is not a function

### ISSUE THREAD

**Issue by youzi** [vigour-io/api#35]
Uncaught error when using the register api in ADM
![image](https://cloud.githubusercontent.com/assets/5662898/13379794/7d070d14-de30-11e5-87c7-879ef7237898.png)
/cc @marcusbesjes

**Comment by youzi** [comment]
Little extra:
![image](https://cloud.githubusercontent.com/assets/5662898/13379833/ae1e7b0c-de31-11e5-87aa-ed7ccf4a5c68.png)
It seems this happens when you have already registered and you try again, but not sure on this.

**Comment by ninjatux** [comment]
fixed in `v1.0.3`
